name: Build Electron App

on:
  workflow_dispatch:
    inputs:
      build_mac:
        description: "Build macOS version"
        required: false
        default: true
        type: boolean
      build_windows:
        description: "Build Windows version"
        required: false
        default: true
        type: boolean

jobs:
  # macOS x64 (Intel)
  build-mac-x64:
    if: ${{ github.event.inputs.build_mac != 'false' }}
    runs-on: macos-13 # Intel-based runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Set npm registry (macOS)
        run: echo -e "@think:registry=https://registry.thinkmoss.com/repository/npm-hosted/\n//registry.thinkmoss.com/repository/npm-hosted/:_authToken=NpmToken.e9591b41-bbe8-3722-aaf2-baa478151db6" > ~/.npmrc

      - name: Show npm config
        run: cat ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build macOS x64
        run: npm run build

      - name: Upload macOS x64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64-build
          path: |
            out/*.dmg

  # macOS arm64 (Apple Silicon)
  build-mac-arm64:
    if: ${{ github.event.inputs.build_mac != 'false' }}
    runs-on: macos-latest # Apple Silicon runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Set npm registry (macOS)
        run: echo -e "@think:registry=https://registry.thinkmoss.com/repository/npm-hosted/\n//registry.thinkmoss.com/repository/npm-hosted/:_authToken=NpmToken.e9591b41-bbe8-3722-aaf2-baa478151db6" > ~/.npmrc

      - name: Show npm config
        run: cat ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build macOS arm64
        run: npm run build

      - name: Upload macOS arm64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: |
            out/*.dmg

  # Windows x64 (64-bit)
  build-windows-x64:
    if: ${{ github.event.inputs.build_windows != 'false' }}
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Set npm registry (Windows)
        run: |
          echo "@think:registry=https://registry.thinkmoss.com/repository/npm-hosted/" > ~/.npmrc
          echo "//registry.thinkmoss.com/repository/npm-hosted/:_authToken=NpmToken.e9591b41-bbe8-3722-aaf2-baa478151db6" >> ~/.npmrc
        shell: bash

      - name: Show npm config
        run: cat ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build Windows x64
        run: npm run build

      - name: Upload Windows x64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-build
          path: |
            out/*.exe
